name: Sonar

# Run for pull request in any branch and push on develop, qa and staging
on:
  pull_request:
  push:
    branches:
      - '*'

env:
  SONAR_PROJECT: ${{ secrets.SONAR_PROJECT }}
  SONAR_URL: ${{ secrets.SONAR_URL }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  sonar:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch unshallow
        run: git fetch --unshallow

      - name: Set Node.js 16.x
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Test and coverage
        run: npm run test-coverage

      - name: Setup sonar scanner
        uses: warchant/setup-sonar-scanner@v5

      - name: Run Sonarqube analysis
        run: |
          echo "NODE_PATH=$(which tsc)" >> $GITHUB_ENV
          sonar-scanner \
            -Dsonar.qualitygate.wait=true \
            -Dsonar.host.url=$SONAR_URL \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.projectKey=$SONAR_PROJECT \
            -Dsonar.nodejs.executable=$(which node) \
            -Dsonar.projectVersion=$(echo $GITHUB_SHA | cut -c1-8) \
            -Dsonar.sonar.sourceEncoding=UTF-8 \
            -Dsonar.sonar.sources=./src \
            -Dsonar.exclusions=dist/**,lib/**,github/**,jest.config.js,./src/main.ts,./src/helpers.ts \
            -Dsonar.sonar.projectBaseDir=. \
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info \
